/*
 * Product
 *
 * 商品管理デモ。OpenAPI Specification については[github](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.4.md#schema-1)を参照。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	// ナカムラ追記：go.mod を作成している場合は、go.mod 内の module で定義した名前を指定する。
	sw "products-manage-server/go"
)

// ナカムラ追記 CORSの許可証を発行する魔法の関数を定義します
func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// アクセスしてきた相手のURL（Origin）をチェックする
		origin := r.Header.Get("Origin")
		// 相手が「3000番」または「8082番」だったら、その相手を許可する
		if origin == "http://localhost:3000" || origin == "http://localhost:8082" {
			w.Header().Set("Access-Control-Allow-Origin", origin)
		}
		// GETやPOSTなどの操作を許可する
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
		// 送られてくるヘッダー（Content-Typeなど）を許可する
		w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")

		// ブラウザからの「事前に安全を確かめる通信（Preflightリクエスト）」への即答
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}

		next.ServeHTTP(w, r)
	})
}

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	router.Use(corsMiddleware)

	log.Fatal(http.ListenAndServe(":8080", router))
}
