openapi: 3.0.4
info:
  title: Product
  description: "商品管理デモ。OpenAPI Specification については[github](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.4.md#schema-1)を\
    参照。"
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: ローカルサーバー
tags:
- name: Product
  description: 商品管理API
paths:
  /products:
    get:
      tags:
      - Product
      summary: 商品一覧取得する
      operationId: getProducts
      responses:
        "200":
          description: 商品の一覧を返す
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
                x-content-type: application/json
  /products/{id}:
    get:
      tags:
      - Product
      summary: 商品をIDで取得する
      operationId: getProductById
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/productID"
      responses:
        "200":
          description: 商品を返す
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: 商品が見つからない場合
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommonError"
components:
  schemas:
    Product:
      required:
      - id
      - name
      - price
      type: object
      properties:
        id:
          $ref: "#/components/schemas/productID"
        name:
          $ref: "#/components/schemas/productName"
        price:
          $ref: "#/components/schemas/price"
      additionalProperties: false
      example:
        id: 1
        name: 商品A
        price: 1000
    productID:
      minimum: 1
      type: integer
      description: 商品ID
      example: 1
    productName:
      maxLength: 20
      type: string
      description: 商品名
      example: 商品A
    price:
      minimum: 0
      type: integer
      description: 商品価格
      example: 1000
    CommonError:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: エラーコード
          example: A3301
        message:
          type: string
          description: エラーメッセージ
          example: エラーメッセージ
