name: unit-test
on:
  pull_request:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ vars.GO_VERSION }}
          # server/go.sumの内容が変わったときだけ、キャッシュを新しく作成する
          cache-dependency-path: server/go.sum
      - run: cd server && go test ./internal/...
